apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zo58vzeha-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zo58vzeha-go 
  name: zo58vzeha-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zo58vzeha-go 
